### ISSUE TITLE
No such file or directory: 'testruns/BestLora/ESM2-150M/test_0_valid_1/model.pt'

### ISSUE THREAD

**Issue by tony9664** [shuaizengMU/PEFT-SP#1]
I cannot find the location of the lora model files. Will these be downloaded automatically by some scripts?

**Comment by nieuwoudtmd** [comment]
I encountered the same issue when attempting to run the prediction script. It seems that none of the trained models are being downloaded automatically. I searched the repository but could not locate any pre-trained models that should be utilised by the script.

**Comment by shuaizengMU** [comment]
> I cannot find the location of the lora model files. Will these be downloaded automatically by some scripts?

I am sorry that I forgot adding link to the models. The models finetuned using LoRA is available at [here](https://mailmissouri-my.sharepoint.com/my?id=%2Fpersonal%2Fzengs%5Fumsystem%5Fedu%2FDocuments%2Fmodels%2FPEFT%2DSP%2Fmodel%2Ezip&parent=%2Fpersonal%2Fzengs%5Fumsystem%5Fedu%2FDocuments%2Fmodels%2FPEFT%2DSP&ga=1)

**Comment by shuaizengMU** [comment]
> I encountered the same issue when attempting to run the prediction script. It seems that none of the trained models are being downloaded automatically. I searched the repository but could not locate any pre-trained models that should be utilised by the script.

Thank you for pointing it out. The models finetuned using LoRA is available at [here](https://mailmissouri-my.sharepoint.com/my?id=%2Fpersonal%2Fzengs%5Fumsystem%5Fedu%2FDocuments%2Fmodels%2FPEFT%2DSP%2Fmodel%2Ezip&parent=%2Fpersonal%2Fzengs%5Fumsystem%5Fedu%2FDocuments%2Fmodels%2FPEFT%2DSP&ga=1)
